#!/bin/bash

# Script to fix HTML file generated by "ng build" to allow that built application can be directly openend in browser
# from file system. It was tested unter Windows in "Git Bash", MacOS and Linux.
#
# This script should be called each time after "npm run build" was executed.

HTML_FILE=docs/index.html

TEMP_FILE=/tmp/FixHtml.html.$$ # append PID to file name to get unique file name


sed -f FixHtml.sed $HTML_FILE > $TEMP_FILE
# Substitution rules to remove particular attributes are defined in file FixHtml.sed

mv $TEMP_FILE $HTML_FILE
